<a href="https://colab.research.google.com/github/DarksterTwilight/Stock_predictor/blob/main/My_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recurrent Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Importing the training set

In [2]:
dataset_train = pd.read_csv('Google_Stock_Price_Train.csv')
training_set = dataset_train.iloc[:, 1:2].values # 1:2 writter as python ignors the upper bound
# values -- it is done so to make a numpy array rather than a simple vector

In [3]:
print(training_set)

[[325.25]
 [331.27]
 [329.83]
 ...
 [793.7 ]
 [783.33]
 [782.75]]


### Feature Scaling

In [4]:
# when ever there is sigmoidal funtion as your output layer Normalization 
# is prefered over standardization
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)

In [5]:
print(training_set_scaled)
print(len(training_set_scaled))

[[0.08581368]
 [0.09701243]
 [0.09433366]
 ...
 [0.95725128]
 [0.93796041]
 [0.93688146]]
1258


### Creating a data structure with 60 timesteps and 1 output

In [6]:
# 60 time step---- at each time step RNN look for data at that time step
# and previous 60 time step to predict it's output......
# this(60) is a hit and try no.
X_train = []
y_train = []
for i in range(60, 1258):
  X_train.append(training_set_scaled[i-60:i, 0]) 
  y_train.append(training_set_scaled[i , 0])
  # upper bound is excluded

X_train, y_train = np.array(X_train), np.array(y_train)


In [7]:
print(X_train.shape)
print(len(X_train))

(1198, 60)
1198


In [8]:
print(y_train)
print(len(y_train))

[0.08627874 0.08471612 0.07454052 ... 0.95725128 0.93796041 0.93688146]
1198


### Reshaping

In [9]:
# reshaping X_train so that new features can be added in future
# currently X_train is an 2-d array
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))


## Part 2 - Building and Training the RNN

### Importing the Keras libraries and packages

In [10]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

### Initialising the RNN

In [11]:
regressor = Sequential()

### Adding the first LSTM layer and some Dropout regularisation

In [13]:
# regularilation for avoid overfitting
regressor.add(LSTM(units= 50, return_sequences= True, input_shape = (X_train.shape[1], 1)))
# units = no. of nurons in this hidden layer
# return seq. true only if u anna add another lstm  to next layer

# Adding Dropout regularisation
regressor.add(Dropout(0.20))
# 20% dropout 20% of nurons will be ignored during each iteration

### Adding a second LSTM layer and some Dropout regularisation

In [14]:
regressor.add(LSTM(units= 50 , return_sequences= True))
# As input shape is being mentioned in first layer there is no need to mention it in 2nd layer
# or anyother mooving forward
regressor.add(Dropout(0.20))

### Adding a third LSTM layer and some Dropout regularisation

In [15]:
regressor.add(LSTM(units= 50 , return_sequences= True))
regressor.add(Dropout(0.20))

### Adding a fourth LSTM layer and some Dropout regularisation

In [16]:
regressor.add(LSTM(units= 50 , return_sequences= False))
# since next is the o/p layer
regressor.add(Dropout(0.20))

### Adding the output layer

In [17]:
regressor.add(Dense(units=1))

### Compiling the RNN

In [18]:
regressor.compile(optimizer= 'adam',loss= 'mean_squared_error')
# as per keras documentation for RNN
# RMSprop is recommended for RNN
# But we will use use adam optimizer (More trusted by me personally)


### Fitting the RNN to the Training set

In [19]:
regressor.fit(X_train,y_train, epochs= 170, batch_size= 32)

Epoch 1/170
38/38 [==============================] - 15s 153ms/step - loss: 0.0384
Epoch 2/170
38/38 [==============================] - 6s 154ms/step - loss: 0.0063
Epoch 3/170
38/38 [==============================] - 6s 151ms/step - loss: 0.0063
Epoch 4/170
38/38 [==============================] - 6s 154ms/step - loss: 0.0061
Epoch 5/170
38/38 [==============================] - 6s 154ms/step - loss: 0.0053
Epoch 6/170
38/38 [==============================] - 6s 154ms/step - loss: 0.0050
Epoch 7/170
38/38 [==============================] - 6s 151ms/step - loss: 0.0052
Epoch 8/170
38/38 [==============================] - 6s 153ms/step - loss: 0.0044
Epoch 9/170
38/38 [==============================] - 6s 152ms/step - loss: 0.0045
Epoch 10/170
38/38 [==============================] - 6s 154ms/step - loss: 0.0051
Epoch 11/170
38/38 [==============================] - 6s 154ms/step - loss: 0.0044
Epoch 12/170
38/38 [==============================] - 6s 151ms/step - loss: 0.0041
Epoch 13/170

## Part 3 - Making the predictions and visualising the results

### Getting the real stock price of 2017

### Getting the predicted stock price of 2017

### Visualising the results